In [1]:
from __future__ import print_function
import torch

x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [2]:
x = torch.rand(5,3)
print(x)

tensor([[0.8454, 0.7933, 0.0345],
        [0.9664, 0.4940, 0.5850],
        [0.0874, 0.7733, 0.9431],
        [0.0027, 0.4112, 0.4116],
        [0.5986, 0.4012, 0.8695]])


In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7688,  0.7677, -2.7504],
        [-1.1027,  2.2175,  0.2712],
        [ 0.7519,  0.9685, -0.5559],
        [-1.5334, -0.8547, -0.1911],
        [-0.4383,  1.2319, -1.4554]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.7772,  1.3386, -2.7459],
        [-0.5485,  2.7050,  0.6010],
        [ 1.4213,  1.0129,  0.0853],
        [-1.4163, -0.1695, -0.0999],
        [ 0.2380,  1.9093, -1.1584]])


In [10]:
print(torch.add(x, y))

tensor([[ 0.7772,  1.3386, -2.7459],
        [-0.5485,  2.7050,  0.6010],
        [ 1.4213,  1.0129,  0.0853],
        [-1.4163, -0.1695, -0.0999],
        [ 0.2380,  1.9093, -1.1584]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.7772,  1.3386, -2.7459],
        [-0.5485,  2.7050,  0.6010],
        [ 1.4213,  1.0129,  0.0853],
        [-1.4163, -0.1695, -0.0999],
        [ 0.2380,  1.9093, -1.1584]])


In [12]:
y.add_(x)
print(y)

tensor([[ 0.7772,  1.3386, -2.7459],
        [-0.5485,  2.7050,  0.6010],
        [ 1.4213,  1.0129,  0.0853],
        [-1.4163, -0.1695, -0.0999],
        [ 0.2380,  1.9093, -1.1584]])


In [13]:
print(x[:, 1])

tensor([ 0.7677,  2.2175,  0.9685, -0.8547,  1.2319])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
print(y)

tensor([ 1.8804,  1.6348, -0.9376,  1.6311, -1.0092, -1.0717, -1.4050, -1.4885,
        -0.8273, -1.4686, -0.1327, -0.2479,  1.7797,  1.5807,  1.5505, -0.6279])


In [16]:
print(x)

tensor([[ 1.8804,  1.6348, -0.9376,  1.6311],
        [-1.0092, -1.0717, -1.4050, -1.4885],
        [-0.8273, -1.4686, -0.1327, -0.2479],
        [ 1.7797,  1.5807,  1.5505, -0.6279]])


In [17]:
print(z)

tensor([[ 1.8804,  1.6348, -0.9376,  1.6311, -1.0092, -1.0717, -1.4050, -1.4885],
        [-0.8273, -1.4686, -0.1327, -0.2479,  1.7797,  1.5807,  1.5505, -0.6279]])


In [21]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.8896])
-1.8895528316497803


In [23]:
print(x)

tensor([-1.8896])


In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
import copy
b = copy.deepcopy(a)
print(b)

tensor([2., 2., 2., 2., 2.])


In [29]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
tensor([2., 2., 2., 2., 2.])


In [30]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [32]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.8896], device='cuda:0')
tensor([-0.8896], dtype=torch.float64)


In [33]:
print(x)
print(y)

tensor([-1.8896], device='cuda:0')
tensor([1.], device='cuda:0')


In [40]:
import torch
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [41]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [42]:
print(y.grad_fn)

In [43]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [44]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [45]:
out.backward()

In [46]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [47]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ -849.3866, -1065.0197,  -157.2678], grad_fn=<MulBackward0>)


In [48]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [49]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
